# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cy2sbml
email: konigmatt@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  cy2sbml: Cytoscape 2 plugin for SBML
baseurl: "/cy2sbml" 
url: "http://matthiaskoenig.github.io" # the base hostname & protocol for your site
twitter_username: konigmatt
github_username:  matthiaskoenig
encoding: utf-8

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

